import React from 'react';
import { Cpu, ImageIcon, CheckCircle2, AlertTriangle } from 'lucide-react';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';
import html2pdf from 'html2pdf.js';
import { Language, ROIParams, ROIResults, MaterialItem } from '../../types';
import { VERDICT_TRANSLATIONS } from '../../constants/translations';

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

const safeFixed = (num: any, digits: number = 2) => {
  if (num === null || num === undefined || isNaN(num)) return "0";
  if (num === Infinity) return "N/A";
  return Number(num).toFixed(digits);
};

export const generatePDF = async (elementId: string, filename: string) => {
  const element = document.getElementById(elementId);
  if (!element) return;
  
  const opt = {
    margin: 0,
    filename: filename,
    image: { type: 'jpeg' as const, quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: 'mm' as const, format: 'a4' as const, orientation: 'portrait' as const }
  };
  
  await html2pdf().set(opt).from(element).save();
};

interface PDFTemplateProps {
  params: ROIParams & { project_id?: string };
  results: ROIResults;
  aiEvaluation: any;
  t: any;
  uploadedImages: string[];
  lang: Language;
}

export const CAPEXReportTemplate: React.FC<PDFTemplateProps> = ({ params, results, aiEvaluation, t, uploadedImages, lang }) => {
  const fmt = (num: any) => (num ?? 0).toLocaleString(undefined, { maximumFractionDigits: 0 });
  const fmtCurrency = (num: any) => '$' + (num ?? 0).toLocaleString(undefined, { maximumFractionDigits: 0 });
  const sf = (num: any, d: number = 0) => safeFixed(num, d);

  const getTranslatedVerdict = (verdict: string) => {
    return VERDICT_TRANSLATIONS[lang]?.[verdict] || verdict;
  };

  const currentMaterialTotal = params.currentMaterials?.reduce((sum, m) => sum + (m.usage * m.fob * (1 + m.loss / 100)), 0) || 0;
  const proposedMaterialTotal = params.proposedMaterials?.reduce((sum, m) => sum + (m.usage * m.fob * (1 + m.loss / 100)), 0) || 0;

  const Header = ({ page }: { page: number }) => (
    <div className="border-b-4 border-emerald-600 pb-6 mb-8 flex justify-between items-end">
      <div>
        <h1 className="text-3xl font-black text-emerald-800 uppercase tracking-tight">{t.capexProposal}</h1>
        <p className="text-[10px] text-zinc-500 font-mono mt-2 tracking-widest">REF: {params.project_id || `${params.shoeModel.toUpperCase()}-${params.date.replace(/-/g, '')}`}</p>
      </div>
      <div className="text-right">
        <div className="flex items-center justify-end gap-2 text-emerald-600 mb-1">
          <Cpu size={20} />
          <span className="font-mono font-black text-xl tracking-tighter italic">FACTORY OS</span>
        </div>
        <p className="text-[10px] text-zinc-400 font-bold uppercase tracking-[0.2em]">Manufacturing Excellence</p>
      </div>
    </div>
  );

  const Footer = ({ page }: { page: number }) => (
    <div className="mt-auto flex justify-between items-center text-[8px] font-bold text-zinc-400 uppercase tracking-widest border-t border-zinc-100 pt-4 pb-4">
      <span>Generated by Factory OS ROI Matrix</span>
      <span>Confidential - Internal Use Only</span>
      <span>Page {page} of 3</span>
    </div>
  );

  return (
    <div id="capex-template" className="bg-white text-black font-sans" style={{ width: '794px' }}>
      
      {/* PAGE 1: General Info & Tech Specs */}
      <div className="p-[40px] flex flex-col" style={{ minHeight: '1123px', pageBreakAfter: 'always' }}>
        <Header page={1} />
        
        <div className="grid grid-cols-2 gap-6 mb-8">
          <div className="overflow-hidden">
            <h2 className="text-[11px] font-black uppercase text-white px-3 py-2 mb-4 tracking-widest" style={{ backgroundColor: '#1e293b' }}>{t.generalInfo}</h2>
            <table className="w-full text-[11px] border-collapse">
              <tbody>
                <tr className="border-b border-zinc-200">
                  <td className="py-2 font-bold text-zinc-500 w-1/3 uppercase tracking-tighter">{t.shoeModel}</td>
                  <td className="py-2 font-medium">{params.shoeModel}</td>
                </tr>
                <tr className="border-b border-zinc-200">
                  <td className="py-2 font-bold text-zinc-500 uppercase tracking-tighter">{t.date}</td>
                  <td className="py-2 font-medium">{params.date}</td>
                </tr>
                <tr className="border-b border-zinc-200">
                  <td className="py-2 font-bold text-zinc-500 uppercase tracking-tighter">{t.equipment}</td>
                  <td className="py-2 font-medium">{params.equipmentName}</td>
                </tr>
                <tr className="border-b border-zinc-200">
                  <td className="py-2 font-bold text-zinc-500 uppercase tracking-tighter">Machine Type</td>
                  <td className="py-2 font-medium">{params.machineType}</td>
                </tr>
                <tr className="border-b border-zinc-200">
                  <td className="py-2 font-bold text-zinc-500 uppercase tracking-tighter">{t.brand}</td>
                  <td className="py-2 font-medium">{params.brand}</td>
                </tr>
                <tr className="border-b border-zinc-200">
                  <td className="py-2 font-bold text-zinc-500 uppercase tracking-tighter">Scope of Work</td>
                  <td className="py-2 font-medium">{params.scopeOfWork}</td>
                </tr>
                <tr className="border-b border-zinc-200">
                  <td className="py-2 font-bold text-zinc-500 uppercase tracking-tighter">{t.machineQuantity}</td>
                  <td className="py-2 font-medium">{params.machineQuantity}</td>
                </tr>
              </tbody>
            </table>
          </div>
          <div className="flex flex-col items-center justify-center border-2 border-zinc-100 rounded-xl p-4 bg-zinc-50/50 shadow-inner">
            {uploadedImages.length > 0 ? (
              <img 
                src={uploadedImages[0]} 
                alt="Machine" 
                className="max-w-full max-h-[60mm] object-contain mb-4 rounded shadow-md"
                referrerPolicy="no-referrer"
              />
            ) : (
              <div className="w-full h-[60mm] flex flex-col items-center justify-center text-zinc-300 italic text-[10px] gap-2">
                <ImageIcon size={32} className="opacity-20" />
                <span>No Image Provided</span>
              </div>
            )}
            <div className="w-full h-[1px] bg-zinc-200 mb-2" />
            <p className="text-[9px] font-black uppercase text-zinc-400 tracking-widest">{t.machinePhoto}</p>
          </div>
        </div>

        <div className="mb-8">
          <h2 className="text-[11px] font-black uppercase text-white px-3 py-2 mb-4 tracking-widest" style={{ backgroundColor: '#1e293b' }}>{t.techSpecs}</h2>
          <table className="w-full text-[11px] border-collapse border-2 border-zinc-800">
            <thead>
              <tr className="bg-zinc-100">
                <th className="border border-zinc-300 p-2 text-left font-black uppercase tracking-tighter text-zinc-600 w-1/3">Specification</th>
                <th className="border border-zinc-300 p-2 text-right font-black uppercase tracking-tighter text-zinc-600 w-1/3">Current State</th>
                <th className="border border-zinc-300 p-2 text-right font-black uppercase tracking-tighter text-zinc-600 w-1/3">Proposed State</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border border-zinc-300 p-2 font-medium">Power Supply (V)</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.currentPowerSupplyV}</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.proposedPowerSupplyV}</td>
              </tr>
              <tr>
                <td className="border border-zinc-300 p-2 font-medium">Power Consumption (kW)</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.currentPowerConsumptionKW}</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.proposedPowerConsumptionKW}</td>
              </tr>
              <tr>
                <td className="border border-zinc-300 p-2 font-medium">Speed (s/prs)</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.currentSpeedSPrs}</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.proposedSpeedSPrs}</td>
              </tr>
              <tr>
                <td className="border border-zinc-300 p-2 font-medium">Unit Price (USD)</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{fmtCurrency(params.currentUnitPrice)}</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{fmtCurrency(params.proposedUnitPrice)}</td>
              </tr>
              <tr>
                <td className="border border-zinc-300 p-2 font-medium">{t.maintenanceCost} (USD/Yr)</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{fmtCurrency(params.currentMaintenanceCostPerYear)}</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{fmtCurrency(params.proposedMaintenanceCostPerYear)}</td>
              </tr>
              <tr>
                <td className="border border-zinc-300 p-2 font-medium">{t.consumablesCost} (USD/Yr)</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{fmtCurrency(params.currentConsumablesCostPerYear)}</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{fmtCurrency(params.proposedConsumablesCostPerYear)}</td>
              </tr>
              <tr>
                <td className="border border-zinc-300 p-2 font-medium">{t.depreciation} (Years)</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.currentDepreciationYears}</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.proposedDepreciationYears}</td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <Footer page={1} />
      </div>

      {/* PAGE 2: Production Data Comparison */}
      <div className="p-[40px] flex flex-col" style={{ minHeight: '1123px', pageBreakAfter: 'always' }}>
        <Header page={2} />
        
        <div className="mb-6">
          <h2 className="text-[11px] font-black uppercase text-white px-3 py-2 mb-4 tracking-widest" style={{ backgroundColor: '#1e293b' }}>{t.prodData} Comparison</h2>
          <table className="w-full text-[10px] border-collapse border-2 border-zinc-800">
            <thead>
              <tr className="bg-zinc-100">
                <th className="border border-zinc-300 p-2 text-left font-black uppercase tracking-tighter text-zinc-600 w-1/3">Metric</th>
                <th className="border border-zinc-300 p-2 text-right font-black uppercase tracking-tighter text-zinc-600 w-1/3">Current State</th>
                <th className="border border-zinc-300 p-2 text-right font-black uppercase tracking-tighter text-zinc-600 w-1/3">Proposed State</th>
              </tr>
            </thead>
            <tbody>
              <tr style={{ backgroundColor: '#1e293b', color: '#ffffff' }}>
                <td colSpan={3} className="border border-zinc-300 p-1 text-[9px] font-black uppercase tracking-widest">IE Data</td>
              </tr>
              <tr>
                <td className="border border-zinc-300 p-2 font-medium">Cycle Time (CT) - s</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.currentCT}</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.proposedCT}</td>
              </tr>
              <tr>
                <td className="border border-zinc-300 p-2 font-medium">Pieces Per Hour (PPH)</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.currentPPH}</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.proposedPPH}</td>
              </tr>
              <tr>
                <td className="border border-zinc-300 p-2 font-medium">Manpower (prs)</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.currentManpower}</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.proposedManpower}</td>
              </tr>
              <tr style={{ backgroundColor: '#1e293b', color: '#ffffff' }}>
                <td colSpan={3} className="border border-zinc-300 p-1 text-[9px] font-black uppercase tracking-widest">Quality Data</td>
              </tr>
              <tr>
                <td className="border border-zinc-300 p-2 font-medium">RFT %</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.currentRFT}%</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.proposedRFT}%</td>
              </tr>
              <tr>
                <td className="border border-zinc-300 p-2 font-medium">Total Defect Rate</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.currentDefectRate}%</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">{params.proposedDefectRate}%</td>
              </tr>
              <tr style={{ backgroundColor: '#1e293b', color: '#ffffff' }}>
                <td colSpan={3} className="border border-zinc-300 p-1 text-[9px] font-black uppercase tracking-widest">Material Cost Summary</td>
              </tr>
              <tr>
                <td className="border border-zinc-300 p-2 font-medium">Total Cost/Pair (USD)</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">${sf(currentMaterialTotal, 4)}</td>
                <td className="border border-zinc-300 p-2 text-right font-mono">${sf(proposedMaterialTotal, 4)}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="mb-6">
          <h2 className="text-[11px] font-black uppercase text-white px-3 py-2 mb-4 tracking-widest" style={{ backgroundColor: '#1e293b' }}>Material Cost Breakdown</h2>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <h3 className="text-[9px] font-bold uppercase text-zinc-500 mb-2">Current State</h3>
              <table className="w-full text-[8px] border-collapse border border-zinc-300">
                <thead>
                  <tr className="bg-zinc-100">
                    <th className="border border-zinc-300 p-1 text-left">Type</th>
                    <th className="border border-zinc-300 p-1 text-right">Usage</th>
                    <th className="border border-zinc-300 p-1 text-right">FOB</th>
                    <th className="border border-zinc-300 p-1 text-right">Cost/Pr</th>
                  </tr>
                </thead>
                <tbody>
                  {params.currentMaterials?.map((m, i) => (
                    <tr key={i}>
                      <td className="border border-zinc-300 p-1">{m.type}</td>
                      <td className="border border-zinc-300 p-1 text-right font-mono">{m.usage}</td>
                      <td className="border border-zinc-300 p-1 text-right font-mono">${m.fob}</td>
                      <td className="border border-zinc-300 p-1 text-right font-mono">${sf(m.usage * m.fob * (1 + m.loss / 100), 4)}</td>
                    </tr>
                  ))}
                  {(!params.currentMaterials || params.currentMaterials.length === 0) && (
                    <tr><td colSpan={4} className="border border-zinc-300 p-1 text-center italic text-zinc-400">No materials added</td></tr>
                  )}
                </tbody>
              </table>
            </div>
            <div>
              <h3 className="text-[9px] font-bold uppercase text-emerald-600 mb-2">Proposed State</h3>
              <table className="w-full text-[8px] border-collapse border border-zinc-300">
                <thead>
                  <tr className="bg-zinc-100">
                    <th className="border border-zinc-300 p-1 text-left">Type</th>
                    <th className="border border-zinc-300 p-1 text-right">Usage</th>
                    <th className="border border-zinc-300 p-1 text-right">FOB</th>
                    <th className="border border-zinc-300 p-1 text-right">Cost/Pr</th>
                  </tr>
                </thead>
                <tbody>
                  {params.proposedMaterials?.map((m, i) => (
                    <tr key={i}>
                      <td className="border border-zinc-300 p-1">{m.type}</td>
                      <td className="border border-zinc-300 p-1 text-right font-mono">{m.usage}</td>
                      <td className="border border-zinc-300 p-1 text-right font-mono">${m.fob}</td>
                      <td className="border border-zinc-300 p-1 text-right font-mono">${sf(m.usage * m.fob * (1 + m.loss / 100), 4)}</td>
                    </tr>
                  ))}
                  {(!params.proposedMaterials || params.proposedMaterials.length === 0) && (
                    <tr><td colSpan={4} className="border border-zinc-300 p-1 text-center italic text-zinc-400">No materials added</td></tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-6 mt-auto mb-8">
          <div className="border-2 border-emerald-600 rounded-xl p-6 bg-emerald-50/50 flex flex-col items-center justify-center shadow-sm">
            <span className="text-[10px] font-black uppercase text-emerald-700 mb-2 tracking-[0.2em]">{t.roi}</span>
            <div className="text-4xl font-mono font-black text-emerald-800 tracking-tighter">
              {sf(results.roiMonths, 1)}
              <span className="text-sm ml-1 uppercase">{t.months}</span>
            </div>
          </div>
          <div className="border-2 border-blue-600 rounded-xl p-6 bg-blue-50/50 flex flex-col items-center justify-center shadow-sm">
            <span className="text-[10px] font-black uppercase text-blue-700 mb-2 tracking-[0.2em]">Cost per Pair Reduction</span>
            <div className="text-4xl font-mono font-black text-blue-800 tracking-tighter">
              -${sf(results.savings.fobImpact, 3)}
            </div>
          </div>
        </div>

        <Footer page={2} />
      </div>

      {/* PAGE 3: AI Evaluation & Signatures */}
      <div className="p-[40px] flex flex-col" style={{ minHeight: '1123px' }}>
        <Header page={3} />
        
        <div className="mb-10">
          <h2 className="text-[11px] font-black uppercase text-white px-3 py-2 mb-4 tracking-widest" style={{ backgroundColor: '#1e293b' }}>{t.investmentVerdict}</h2>
          {aiEvaluation ? (
            <div className="border-2 border-zinc-200 rounded-xl p-6 bg-zinc-50/30">
              <div className="flex items-center gap-3 mb-4">
                <span className="text-xs font-black uppercase text-zinc-400 tracking-widest">{t.verdict}:</span>
                <span className={cn(
                  "px-4 py-1 text-xs font-black uppercase tracking-[0.2em] rounded",
                  aiEvaluation.verdict === 'Strongly Recommend' || aiEvaluation.verdict === 'Duyệt Gấp' ? "bg-emerald-600 text-white" : 
                  aiEvaluation.verdict === 'Consider with Caution' || aiEvaluation.verdict === 'Cân Nhắc Kỹ' ? "bg-amber-500 text-black" : "bg-red-600 text-white"
                )}>
                  {getTranslatedVerdict(aiEvaluation.verdict)}
                </span>
              </div>
              <p className="text-xs text-zinc-700 leading-relaxed mb-6 font-medium italic border-l-4 border-zinc-300 pl-4">
                {aiEvaluation.summary}
              </p>
              <div className="grid grid-cols-2 gap-8">
                <div className="bg-white p-4 rounded-lg border border-zinc-100 shadow-sm">
                  <h3 className="text-[10px] font-black uppercase text-emerald-700 mb-3 flex items-center gap-2">
                    <CheckCircle2 size={14} />
                    {t.pros}
                  </h3>
                  <ul className="text-[10px] text-zinc-600 space-y-2">
                    {aiEvaluation.pros?.map((p: string, i: number) => (
                      <li key={i} className="flex items-start gap-2">
                        <span className="text-emerald-500 font-bold mt-[-2px]">•</span>
                        <span>{p}</span>
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="bg-white p-4 rounded-lg border border-zinc-100 shadow-sm">
                  <h3 className="text-[10px] font-black uppercase text-red-700 mb-3 flex items-center gap-2">
                    <AlertTriangle size={14} />
                    {t.cons} / {t.risks}
                  </h3>
                  <ul className="text-[10px] text-zinc-600 space-y-2">
                    {[...(aiEvaluation.cons || []), ...(aiEvaluation.risks || [])].map((c: string, i: number) => (
                      <li key={i} className="flex items-start gap-2">
                        <span className="text-red-500 font-bold mt-[-2px]">•</span>
                        <span>{c}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          ) : (
            <div className="text-center py-10 border-2 border-dashed border-zinc-200 rounded-xl text-zinc-400 text-xs font-bold uppercase tracking-widest bg-zinc-50/50">
              Analysis Pending
            </div>
          )}
        </div>

        <div className="mt-auto pt-12">
          <div className="border-2 border-zinc-800 rounded-lg overflow-hidden">
            <table className="w-full text-[10px] border-collapse">
              <tbody>
                <tr>
                  <td className="w-1/5 text-center border-r border-zinc-200 p-4">
                    <div className="h-20 mb-3 bg-zinc-50/30 rounded border border-dashed border-zinc-200"></div>
                    <p className="font-black uppercase tracking-tight text-zinc-800">{t.preparedBy}</p>
                    <p className="text-[8px] text-zinc-400 font-bold uppercase mt-1">Date: ____/____/____</p>
                  </td>
                  <td className="w-1/5 text-center border-r border-zinc-200 p-4">
                    <div className="h-20 mb-3 bg-zinc-50/30 rounded border border-dashed border-zinc-200"></div>
                    <p className="font-black uppercase tracking-tight text-zinc-800">{t.verifiedBy}</p>
                    <p className="text-[8px] text-zinc-400 font-bold uppercase mt-1">Date: ____/____/____</p>
                  </td>
                  <td className="w-1/5 text-center border-r border-zinc-200 p-4">
                    <div className="h-20 mb-3 bg-zinc-50/30 rounded border border-dashed border-zinc-200"></div>
                    <p className="font-black uppercase tracking-tight text-zinc-800">{t.approvedBy}</p>
                    <p className="text-[8px] text-zinc-400 font-bold uppercase mt-1">Date: ____/____/____</p>
                  </td>
                  <td className="w-1/5 text-center border-r border-zinc-200 p-4">
                    <div className="h-20 mb-3 bg-zinc-50/30 rounded border border-dashed border-zinc-200"></div>
                    <p className="font-black uppercase tracking-tight text-zinc-800">{t.financeMgr}</p>
                    <p className="text-[8px] text-zinc-400 font-bold uppercase mt-1">Date: ____/____/____</p>
                  </td>
                  <td className="w-1/5 text-center p-4">
                    <div className="h-20 mb-3 bg-zinc-50/30 rounded border border-dashed border-zinc-200"></div>
                    <p className="font-black uppercase tracking-tight text-zinc-800">{t.gm}</p>
                    <p className="text-[8px] text-zinc-400 font-bold uppercase mt-1">Date: ____/____/____</p>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        
        <Footer page={3} />
      </div>
    </div>
  );
};
